apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agentloom

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - job.yaml
  - cronjob.yaml
