{{- if and (trimAll " \n" .Values.workflow.definition) (not .Values.workflow.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentloom.fullname" . }}-workflow
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentloom.labels" . | nindent 4 }}
data:
  workflow.yaml: |
    {{- .Values.workflow.definition | nindent 4 }}
{{- end }}
